### ISSUE TITLE
[Question] What is your plan about "decompressing" file contents?

### ISSUE THREAD

**Issue by azisyus** [derplayer/LoGHTools#1]
I was working in same game, i can parse files by their meta, pack them back (datatable.mvx)  and game still works but i have no idea about those compressed files, i can see there are names of characters but as i said i have no idea about how they compressed or their compressing algorithm.

**Comment by derplayer** [comment]
You have used the decompressed unfinnished translation database.mvx?
Because my app can decompress all contents from all file containers. There is a "microvision" compression/decompression library compiled into the executable, and you can reuse those functions. Thats what i am doing. The editing of those decompressed files is a different story because of their unknown structures, but they are 100% decompressed. (You can see that there are some jpegs in there for example that are clean decompressed)

![Alt text](https://i.imgur.com/0sZpnDQ.png "Preview")

Are you reinterpreting the header metadata or do you just passtrough? Can you upload what you have done?

**Comment by azisyus** [comment]
First of all this is my repo; https://gitlab.com/azizyus/logh-arc-packer

I was using original datatable.mvx file which is i found in game files and also i know that "unfinished translation datatable.mvx" and i translated more but than i decided to conquer whole game and that will be much more easy for future modifications. I'm not using any "microvision" dll or something like that and i didnt even know something like that exist until now.  

As you can see i can extract files from datatable.mvx and pack them back as new "my.datatable.arc" which is almost same file with datatable.mvx. I know which byte represents size of files in "arc" file so it shouldnt be problem changing content of file as long as its something understandable by game engine, actually i know meaning of whole (almost) "meta" part and that means i am not just reading meta, i know how to produce new metadata.

![resim](https://user-images.githubusercontent.com/26818892/68805889-c4263500-0675-11ea-9174-fd6531b52d2f.png)

Original datatable.mvx
![resim](https://user-images.githubusercontent.com/26818892/68807623-35b3b280-0679-11ea-85e5-f8edf6a17539.png)

My datatable.mvx
![resim](https://user-images.githubusercontent.com/26818892/68807658-46fcbf00-0679-11ea-89d2-626280a6baef.png)







My problem is, i dont know meaning of those bytes, there is some characters names and directory names etc etc... But it is "compressed" or "encoded". If i can "decompress" content of a single file, packing them back isnt problem, we can change their size, we can change whole image or even we can add new file to "arc" file. It shouldnt matter, at least thats what i hope.
![resim](https://user-images.githubusercontent.com/26818892/68806181-63e3c300-0676-11ea-9a77-4dfef52176f9.png)

**Comment by derplayer** [comment]
The microvision dll is done by ripping out code from executeable. Microvision is the company that has developed the game and they have two to three compression variants if i remember correctly? ARC0,ARC1 and ARC2?

And yes the database is compressed with microvisions ARC1 compression variant + encoded bin files with strings in sjis encoding. I have used the orginal database.mvx and decompressed it to show you. It contains  some extra stuff, but you can work with it. You just need to change sjis encoding in wxMEdit.

![Alt text](https://i.imgur.com/FWgO3Hf.png "Preview")

**Comment by azisyus** [comment]
Sorry for delay, we have too much timezone difference i believe but thats another story.

Good news, i can change loading images but still its not perfect. 

![example](https://user-images.githubusercontent.com/26818892/68866171-12cee000-0705-11ea-8b97-5b3e64e4da8b.png)


I know that shift-jis thing which is 16bit encoding, i dont know is there any ARC example other than ARC1, i didnt check other visual novels but probably they are exist somewhere else, my point is if it is same thing with other ARC files (i mean any other game),[ why they couldnt parse it](https://github.com/vn-tools/arc_unpacker/issues/122)? Is there more game made by "microvision"?

And you mean you can unpack compressed content of datatable.mvx and pack it back without compression which is still usable file by game?

**Comment by derplayer** [comment]
Well i looked up some games and they use similar formats for files "like *.BBQ in iDOLM@STER Dearly Stars" but the compression is different. And i didnt saw other examples that arent ARC1, but i saw that the microvision library has defined identifier for it in executeable so they exist somewhere.

Yes unpack contents and repack should work, when you change the compression variant to uncompressed. (like in the unfinnished database.mvx that is also in uncompressed mode)
But my header stuff has missing stuff, so it crashes.

**Comment by azisyus** [comment]
Interesting, i can unpack and pack back compressed data and game still works, may i see your datatable.mvx? I believe i can help about that.

**Comment by derplayer** [comment]
Sorry for the delay im pretty sick right now. With my decompressed repack the game just turns off without error message. I hadn't time to look into it deeper.
https://puu.sh/EEXfu/12aaa7e0e9.mvx

**Comment by azisyus** [comment]
I hope you get well soon.

I already find wrong things about your datatable.mvx, how does that "microvision" decompresser works? What compiler did you use?  

First of all every metadata is 32 byte which is actually looks like 2 line, as you can see those are your data start addresses of your file (character_spec.bin) in ARC, when you go that address there is something different, your addresses are wrong also probably your file size is wrong too, i didn't check it but it looks wrong.

![e1](https://user-images.githubusercontent.com/26818892/68974565-21e78800-0802-11ea-8575-e9a98e5a187e.png)

As you can see it starts from 0x4A0 but they should be in 0x480 because your metadata says like that.

![e2](https://user-images.githubusercontent.com/26818892/68974567-21e78800-0802-11ea-9686-c0d4fa795878.png)

Also file data is more like blocks in ARC, i mean lets say your character_spec.bin file is 3236 byte but it should be 4096, i don't know why but they are exist as blocks, thats just my theory, but it works.

I am planing to decompress everything and repack because when you repack file as compressed also you need size of decompressed in metadata which is bad for us because we don't know how to compress data for ARC.

**Comment by derplayer** [comment]
Thanks. Decompressor is something LZSS based, because before the ripped function i tried some lzss variants and could decompress it partially. There is some decompiled code in my repo if it helps you. As compiler for the dll i have used mingw gcc 5 with codeblocks. The codeblocks project file is also in my repo so if you want to play with it go for it. MSVC will not work, because of DEP workaround.

And yeah i see... need to recheck everything gee hahaha
The files are in blocks becase the game filereader reads all files in 128 byte chunks.

**Comment by azisyus** [comment]
128 byte chunks makes sense, i can make smaller ARC files in future but its not my priority. 

I wonder is this [function ](https://github.com/derplayer/LoGHTools/blob/master/MicrovisionDLL/main.c#L132)really working? What exactly dump.bin? I guess it represents character_spec.bin? I would like to separate repacker and decompresser and i think all i need is proper C decompresser.

[Also it doesnt looks like it can allocate memory for read (dump.bin) file](https://github.com/derplayer/LoGHTools/blob/master/MicrovisionDLL/main.c#L103), i believe you made some experiment in code? If you did, would you mind to share working version of this decompiled code?

**Comment by derplayer** [comment]
The main function is very hacky, i used it only for dirty testing. Yes dump.bin was just a dump of one of files from an *.mvx. You need to use the microvision_decompress() directly, that wrapps everything else. I use it with Marshalling in C# and everything works without any problems. The code looks weird because it abuses C so that it can execute code from the data segment, that is just ripped out assembler code put into an array. But it works 100%.

```
byte[] pInBuffer = localToc.Data;

//allocate unmanaged memory
IntPtr inputBuffer = Marshal.AllocHGlobal(pInBuffer.Length * sizeof(byte));
Marshal.Copy(pInBuffer, 0, inputBuffer, pInBuffer.Length);

IntPtr result = microvision_decompress(inputBuffer, localToc.Size + 1, localToc.Zsize);
localToc.DataDecompressed = new byte[localToc.Size];
Marshal.Copy(result, localToc.DataDecompressed, 0, localToc.Size);

//free allocated memory
Marshal.FreeHGlobal(inputBuffer);
microvision_free(result);
```

You need the size/compressed size from table of contents from an mvx file to make a decompression call.

**Comment by azisyus** [comment]
I found why i couldn't make it work that microvision DLL, because i was using wrong compiler, as you said it works but the problem is, output doesnt look good, i mean its obvious there is decompressed data but why is there difference between C# and and C output? They have to be same because i gave them same unpacked character_spec.bin file. I wonder which one of them is truly right decompression but i believe i will find out in upcoming days.




![diff2](https://user-images.githubusercontent.com/26818892/69199148-34d2c300-0b48-11ea-946d-c1342eff57c6.png)







Also the first string we can translate is "Invalid Value" (無効値) but where is it? That means decompression is wrong.

![resim](https://user-images.githubusercontent.com/26818892/69199982-d3602380-0b4a-11ea-976b-60da83816357.png)

![resim](https://user-images.githubusercontent.com/26818892/69200104-32259d00-0b4b-11ea-926d-cfe5dcaa5948.png)

**Comment by derplayer** [comment]
Yeah, i see something is wrong it decompresses it correctly, but cuts about half of the filebuffer?
"フレデリカ" is the first string in character_spec but in unfinnished translation it is somewhere in the middle of the file.
Did you got any further?

**Comment by azisyus** [comment]
You are right, it decompresses correctly. What happens when you change read mode from "r" to "rb"? The result changes, but why does it change and more importantly both of decompression results are actually part of character_spec.bin. Also my decompressed output is is limited to 4096 byte which is feels like its not a random number.


If i read with "r" mode i can see the first string we can translate but its just gives 300 byte decompressed output, with "rb" mode i can get same result as yours. Decompressed output should be 10974 (0x2ade) byte because of metadata.
 
![bad decompressed](https://user-images.githubusercontent.com/26818892/69599111-e9735580-101c-11ea-8eab-a42683889431.png)

**Comment by derplayer** [comment]
Strange, maybe the trick is to decompress in chunks like only each 4096 bytes and then putting everything together?

**Comment by azisyus** [comment]
Compressed character_spec.bin file is already smaller than 4096 but output is bigger than 4096 (its 10974 byte), so i tried a smaller file like a msg.bin which is smaller than 4096 byte also its output is smaller than 4096 byte and i have successful decompression result, i think there is a specific parameter to determine the output size of decompression process but i have no idea where could be.

**Comment by derplayer** [comment]
Ok, i rewrote the lzss compression stuff in C# with help of an friend and dropped the broken DLL. and now it works correctly.
![works now](https://i.imgur.com/uXlMO5e.png)

**Comment by azisyus** [comment]
It's good to hear you are able to decompress files correctly, i have almost abandoned my project because of my workload. After all looks like there is no much thing to do except archiving game files back. Does the game work with your decompressed character_spec.bin file? What did you learn about header flags?

**Comment by derplayer** [comment]
Yeah i have myself much todo but now got to it after months. Didn't tested it, because my re-packer is still not fixed. About header flags i think i dont know more than you, but it should be enough to apply changes and run it in game.

**Comment by azisyus** [comment]
As you said the information about flags we have should be enough to repack files and run the game. I would like to rewrite your re-packer in my free time instead of wasting time with mine.

**Comment by derplayer** [comment]
Sure, feel free to fork/commit. Just remember, that this one was more of an hacky research code project if it would be possible to do such tools, so there was no time for stuff like propper code structure/UI or an Translation String editor. It would need a total rewrite 😆 
My plan is to do something like my other mod project/s [(like SHD for example),](https://github.com/derplayer/ShenmueHDTools) later on - a full fleged modkit, so that one could for example translate everything ingame or just simply mod it.

**Comment by azisyus** [comment]
I have completed basic example of decompression and repacking process in my [fork](https://github.com/azisyus/LoGHTools), i tested first stage of game and it works as expected with decompressed and repacked datatable.mvx. The project is basically a garbage and should be rewritten, what kind of structure would you like to follow?

**Comment by derplayer** [comment]
Sorry didn`t had time to write back. I see you have already done some nice stuff in your fork. Great! I will close this ticket because decompression works now and merge your pull.
